services:
  ayushchugh.com-postgres-service:
    image: postgres
    platform: linux/amd64
    container_name: ayushchugh.com-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ayushchugh.com
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ayushchugh.com-postgres-data:/data

volumes:
  ayushchugh.com-postgres-data:
